language: python
python:
  - "3.6"
install:
    - "pip install pytest"
    - "pip install pytest-cov" #This plugin produces coverage reports
 #   - "pip install pytest-xdist" #For distributed testing support install pytest-xdist
script:
  - python -m pytest Problem_1/tests/
#  - python runner.py
