#!/usr/bin/python

import time
from utils.utils \
    import print_time_log, \
    calc_pentagonal_number, \
    is_pentagonal


def main(index: int):
    """
    Triangle, pentagonal, and hexagonal numbers
    are generated by the following formulae:

        Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
        Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
        Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.
    Find the next triangle number that is
    also pentagonal and hexagonal.

    Every hexagonal number is a triangular number since:
    r(2r-1)=1/2(2r-1)[(2r-1)+1].
    Source: http://mathworld.wolfram.com/HexagonalNumber.html

    Every pentagonal number is 1/3 of a triangular number.
    Source: http://mathworld.wolfram.com/PentagonalNumber.html
    :return:
    """

    start_time = time.time()

    while True:
        pentagonal = calc_pentagonal_number(index)
        triangular = pentagonal * 3

        if is_pentagonal(triangular):
            print_time_log(start_time, triangular)
            return triangular
        index += 1
